language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - xvfb

before_script:
  - npm install

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm run test
