export default {
  COPY: 'SEARCH:COPY',
  COPIED: 'SEARCH:COPIED',
  NOTCOPIED: 'SEARCH:NOTCOPIED',
  CHANGEPAGE: 'APP:CHANGEPAGE',
  HIDE: 'APP:HIDE',
  RESET: 'APP:RESET',
  SHORTCUT: 'APP:SHORTCUT'
};
